### PR TITLE
Add correct abbreviation for "Western Indonesian Time" time zone

### PR DESCRIPTION
**Pull request by afcapel**
We are abbreviating "Western Indonesia Time" as WIT, but the right abbreviation is "WIB", from the Indonesian name "       "Waktu Indonesia Barat". WIT actually means "Eastern Indonesia Time", which is 2 hours apart.

See https://en.wikipedia.org/wiki/Time_in_Indonesia

### CODE REVIEW

**Comment by josefarias** [comment]
@afcapel thanks for this!

I'm considering replacing the library's bespoke time zone parsing with the browser's native [`Intl.DateTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat).

This has the upside of relaying this and other edge cases to the browser. But it has the downside of not correctly parsing some time zones like `Central European Standard Time` and `Western Indonesia Time`. Although it does have sensible fallbacks and will display e.g. `GMT+7` instead of incorrect abbreviations like `CEST` and `WIT`.

I think this would be preferable to adding an `if` statement for every known edge case. What do you think?

Here are how some of the known troublesome time zones would behave with the new implementation:
### No location sensor applied
```js
>> time = Date.parse("2011-01-01T12:00:00-05:00")
>> new Date(time).toLocaleString(undefined, { timeZoneName: "short" }).split(" ").pop()
=> 'CST' // ✅ This is correct for my current location
```

### Location sensor applied for [Anchorage](https://github.com/basecamp/local_time/issues/94)
```js
>> new Date(time).toLocaleString(undefined, { timeZoneName: "short" }).split(" ").pop()
=> 'AKST' // ✅ 
```

### Location sensor applied for [Paris](https://github.com/basecamp/local_time/issues/105) when not in summer
```js
>> new Date(time).toLocaleString(undefined, { timeZoneName: "short" }).split(" ").pop()
=> 'GMT+1' // 🆗 Ideally would be 'CET'
>> new Date(time).toLocaleString(undefined, { timeZoneName: "long" })
=> '1/1/2011, 6:00:00 PM Central European Standard Time'
```

### Location sensor applied for [Hawaii](https://github.com/basecamp/local_time/pull/102)
```js
>> new Date(time).toLocaleString(undefined, { timeZoneName: "short" }).split(" ").pop()
=> 'HST' // ✅ 
```

### Location sensor applied for [Jakarta](https://github.com/basecamp/local_time/pull/141)
```js
>> new Date(time).toLocaleString(undefined, { timeZoneName: "short" }).split(" ").pop()
=> 'GMT+7' // 🆗 Ideally would be 'WIB'
>> new Date(time).toLocaleString(undefined, { timeZoneName: "long" })
=> '1/2/2011, 12:00:00 AM Western Indonesia Time'
```

**Resources for future reference**
[List of tz database time zones](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
[Time zone abbreviations](https://www.timeanddate.com/time/zones/)
[Changing your location in Chrome devtools](https://developer.chrome.com/docs/devtools/settings/locations/)
[Using Chrome sensors](https://developer.chrome.com/docs/devtools/sensors/#open-sensors)

**Comment by afcapel** [comment]
@josefarias do we know of any time zones that need special treatment other that `Central European Standard Time` and `Western Indonesia Time`? No one likes ad-hoc conditionals in the code base, but if it's only two cases, I'm fine with them. Showing `GMT+1` is a poorer user experience than `CET`, IMO.

**Comment by josefarias** [comment]
@afcapel yeah Anchorage and Hawaii have also been reported separately. I like the idea of delegating to the browser because it's one less thing this library has to do - and it would update automatically as the browser improves locale support, which is useful for other edge cases that haven't been reported.

What do you think about changing the implementation to Intl, as suggested, but also adding those two ad-hoc conditionals for the two timezones we know it doesn't handle well?

**Comment by josefarias** [comment]
Now that I think about it, we could even fall back to the current implementation if the Intl result returns a variation of GMT+/-x

**Comment by afcapel** [comment]
> Now that I think about it, we could even fall back to the current implementation if the Intl result returns a variation of GMT+/-x

Sounds good 👍 

Otherwise mapping GMT+X to time zone is going to be tricky because for a given GMT+x there might be several different time zones with different DST settings.

**Comment by ykamin-booth** [comment]
Not to pile on, but the gem also shows SST for Singapore Standard Time when that is more accurately the abbreviation for Samoa Standard Time. Singapore's abbreviations is more commonly SGT.

**Comment by josefarias** [comment]
> Not to pile on, but the gem also shows SST for Singapore Standard Time when that is more accurately the abbreviation for Samoa Standard Time. Singapore's abbreviation is more commonly SGT.

@ykamin-booth thanks for letting us know! I'm planning on working on this in a couple of weeks and will include SGT in that work.

**Comment by josefarias** [comment]
https://github.com/basecamp/local_time/pull/142

**Comment by josefarias** [comment]
Closing as https://github.com/basecamp/local_time/pull/142 has been merged, that should address this issue

**Pull request closed without merging**
