### PR TITLE
I18n

### PR DESCRIPTION
**Pull request by kevcha**
Hi, 
following https://github.com/basecamp/local_time/pull/50, I tried to add i18n with @javan recommendations.

The basic idea is to let people override javascript object `LocalTime.i18n` with custom labels.

Let me know what do think about this :)

### CODE REVIEW

**Comment by Xosmond** [comment]
Waiting! :)))

**Comment by javan** [comment]
Thanks @kevcha! I merged your branch into #55 and made a quite a few changes. I'm planning to release it in version 2.0. Let me know what you think.

**Comment by kevcha** [comment]
Sorry for the delay :/ Your PR #55 looks really good ! :+1:

**Comment by williamparso** [comment]
Can anyone explain how to do this? i try loading the gem this way gem 'local_time', git: 'https://github.com/basecamp/local_time', branch: '2-0'
then i write inn my assets/application.js
 #= require local_time
#= require local_time_language in this one i set the LocalTime.i18n as it says in the readme and it seems i actually setting them fine as i see in console:

 Object {weekdays: "Domingo Lunes Martes Miercoles Jueves Viernes Sabado", months: "Enero Febrero Marzo Abril Mayo Junio Julio Agosto Septiembre Octubre Noviembre Diciembre" .. ETC

but i do in my view local_time 2.months.from_now to test andthe result is still in english, can someone help me on this?

**Pull request closed without merging**
