### PR TITLE
2.0

### LINKED ISSUE #56: Consider precompiling local_time.js to eliminate the coffee-script gem dependency
It would eliminate the coffee_script dependency, which is currently required.

### LINKED ISSUE #63: The gem is slow in converting
Sometimes the gem takes maybe more than a minute to convert the text using the `local_time_ago` helper. Anyone aware about this and/or knows a solution? I'm also using turbolinks, if that can be an issue.

### LINKED ISSUE #66: Some kind of cache
Hi,
I'm using local time like this:
`<td><%= local_time(node.last_seen) %></td>`
And when I'm opening the page I see non-converted time:
`<time datetime="2017-03-30T17:36:39Z" data-local="time" data-format="%B %e, %Y %l:%M%P">March 30, 2017  5:36pm</time>`
After I'm pressing F5 to refresh the page:
`<time datetime="2017-03-30T17:36:39Z" data-local="time" data-format="%B %e, %Y %l:%M%P" title="March 30, 2017 at 8:36pm RST" data-localized="true">March 30, 2017 8:36pm</time>`

So, it's smells like some kind of caching. Maybe I'm cooking gem in wrong way?

Thank you.

### LINKED ISSUE #70: Publish javascript to npm?
I'm in the process of converting a large Rails project over to Webpacker and we have `local_time` as a dependency. Hence, it'd be great to make the javascript inthis project available via NPM. Looks like this would require a release step to build JS from the CoffeeScript source, make compatible with requireJS/ES6-modules, and coordinate publishing to Rubygems and NPM, or perhaps having a separate repo altogether. 

Is this something you'd consider for this project?

### PR DESCRIPTION
**Pull request by javan**
- Adds i18n support (branched from #53)
- Uses `MutationObserver` instead of listening for various Turbolinks and jQuery events
- Allows updating a single element with `LocalTime.process(element)`
- Refactors code into multiple files, logical pieces

Todo:
- [x] Update README
- [x] Drop `coffee-rails` dependency, bundle compiled `local-time.js` instead
- [x] Publish npm package

---

Fixes #54 
Fixes #56 
Fixes #60 
Fixes #63
Fixes #66
Fixes #70
Fixes #71
Closes #49
Closes #50 
Closes #53

### CODE REVIEW

**Comment by grk** [comment]
I was testing this branch because we need I18n support, and I ran into an issue with PageObserver. It's observing on `document.body`, but turbolinks throws out the body and replaces it with a new one, so no callbacks were being fired. A quick fix would be to observe on `document.body.parentElement` (so `<html>`), but I'm not sure if that's the right way.

Do you have any suggestions how to work around that? Or am I doing something wrong?

**Comment by javan** [comment]
@grk Fixed in 9fae4257e3adcedd9f10d01f591b1dc6b549ca9d. Mind giving it a try?

**Comment by grk** [comment]
@javan yes, this fixes the problem. Thanks!

**Comment by brandonhilkert** [comment]
Hi there! Thanks so much for this gem. We're using with Rails 5 and it's not working with the new Turbolinks b/c of the `page:change`. This looks like it'll do the trick. Was curious if you're going to release soon or if there was something I could do to help the cause. Thanks again 👍

**Comment by javan** [comment]
Hey @brandonhilkert, thanks!

I'd like to explore using [`Date#toLocaleString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString) (and [`Date#toLocaleDateString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString), [`Date#toLocaleTimeString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString)) to localize timestamp formats natively, and to avoid the need for defining translations client side where possible. I'm not sure it will pan out, but it's worth an investigation.

Other than that, I think this branch is stable for use and could be shipped soon. Just need to polish the docs.

**Comment by brandonhilkert** [comment]
@javan Sounds good! Branch worked well locally, I'll go with that for now. Curious was Basecamp 3 is using for local time display if it's not this...

**Comment by javan** [comment]
Basecamp 3 is running on https://github.com/basecamp/local_time/pull/49 and using its own MutationObserver wrapper to process elements:
```coffee
BC.observe 'time[datetime]', (element) ->
  LocalTime.updateElement(element)
```
This branch obviates it by incorporating a MutationObserver. We could switch over and just haven't gotten around to it.

**Comment by akashaggarwal7** [comment]
Uncaught TypeError: LocalTime.relativeTimeAgo is not a function
This error didn't show up in the master branch.

**Comment by javan** [comment]
@akashaggarwal7, you can create `LocalTime.RelativeTime` instances directly now. See [relative_time.coffee](https://github.com/basecamp/local_time/blob/master/lib/assets/javascripts/src/local-time/relative_time.coffee) for its full API.

screen shot 2017-08-07 at 11 34 26 am

**Comment by brandonhilkert** [comment]
Thanks for this! ☮️

**Pull request merged**
